---
# FILE KONFIGURASI UTAMA: host, IP, user SSH, port, jumlah container, dan CPU.
# User SSH dapat ditetapkan global atau dioverride per host.
all:
  vars:
    # Ganti sesuai image VM: ubuntu, debian, root, cloud-user, dan sebagainya.
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
    ansible_become_method: sudo

    backend_container_count: 4
    backend_first_port: 8081
    backend_internal_port: 8080
    desired_cpus_per_container: 2.0
    cpu_shares_when_oversubscribed: 1024

    app_image: local/fasthttp-backend
    app_image_tag: "1.0.0"
    app_dir: /opt/fasthttp-backend
    app_network: fasthttp-network
    go_builder_image: golang:1.26-alpine
    runtime_image: alpine:3.23
    fasthttp_version: v1.72.0

    cleanup_orphan_containers: true

  children:
    fasthttp_backends:
      hosts:
        FastHTTP-Backend-01:
          ansible_host: 10.221.67.69
        FastHTTP-Backend-02:
          ansible_host: 10.221.67.148
        FastHTTP-Backend-03:
          ansible_host: 10.221.67.124
        FastHTTP-Backend-04:
          ansible_host: 10.221.67.68

        # Contoh override user hanya untuk satu host:
        # FastHTTP-Backend-05:
        #   ansible_host: 10.221.67.200
        #   ansible_user: debian
